// Generated by `weft codegen`. Do not edit by hand.
/* eslint-disable */

declare module 'weft' {
  interface WorkflowRegistry {
    "welcome": { input: { "name": string; }; output: { "greeting": string; } };
  }
}

export {};
